### PR TITLE
Add roslibpy package

### PR DESCRIPTION
**Pull request by KenwoodFox**
This is a handy package for facilitating ROS communication
to a coprosessor or similar without having to install an
entire ros stack on the RIO

### CODE REVIEW

**Comment by virtuald** [comment]
You'll need to add any native dependencies to the list also.... which, watching github actions building the wheel, looks like a bunch of things.

Also. It looks like it depends on cryptography, and I didn't build ssl for the roborio because of openssl versioning issues (though, the build crossenv likely has it enabled).

**Comment by virtuald** [comment]
Looking closer, it appears roslibpy is a pure python package, so it isn't necessary for us to publish a wheel of it for you to use it with robotpy-installer. Some of its dependencies are however:

- cffi
- cryptography
- zope.interface

`cffi` should be doable if you want to spend the time on it. cryptography requires a working rust toolchain, and I'm not willing to spend the time on making that work.

`zope.interface` is trivial and I just pushed a commit that should build it and push it shortly. It's possible that might be enough to download and use roslibpy.

**Comment by virtuald** [comment]
Looks like it downloads:

```
Saved ... pip_cache/roslibpy-1.2.1-py2.py3-none-any.whl
Saved ... pip_cache/autobahn-19.6.1-py2.py3-none-any.whl
Saved ... pip_cache/Twisted-21.7.0-py3-none-any.whl
Saved ... pip_cache/attrs-21.4.0-py2.py3-none-any.whl
Saved ... pip_cache/Automat-20.2.0-py2.py3-none-any.whl
Saved ... pip_cache/constantly-15.1.0-py2.py3-none-any.whl
Saved ... pip_cache/hyperlink-21.0.0-py2.py3-none-any.whl
Saved ... pip_cache/incremental-21.3.0-py2.py3-none-any.whl
Saved ... pip_cache/six-1.16.0-py2.py3-none-any.whl
Saved ... pip_cache/txaio-21.2.1-py2.py3-none-any.whl
Saved ... pip_cache/typing_extensions-4.0.1-py3-none-any.whl
Saved ... pip_cache/zope.interface-5.4.0-cp310-cp310-linux_armv7l.whl
Saved ... pip_cache/idna-3.3-py3-none-any.whl
Saved ... pip_cache/setuptools-60.5.0-py3-none-any.whl
Successfully downloaded roslibpy autobahn twisted attrs Automat constantly hyperlink incremental six txaio typing-extensions zope.interface idna setuptools
```

**Comment by KenwoodFox** [comment]
Thanks for jumping on this! Is this good? Bad? I see that its closed with unmerged commits. Crypto has always been a thorn in my side too :/ Is that keeping us from getting roslibpy in?

**Comment by virtuald** [comment]
@KenwoodFox roslibpy doesn't need to be added to robotpy-wheels, only things that aren't pure python need to be added. In theory you should be able to install roslibpy without any problems -- I haven't tried it.

**Comment by KenwoodFox** [comment]
> @KenwoodFox roslibpy doesn't need to be added to robotpy-wheels, only things that aren't pure python need to be added. In theory you should be able to install roslibpy without any problems -- I haven't tried it.

Oh! Right got you, the mention of crypto with rust compilation worried me for a sec. Ill let you know how it goes and reopen if i find a solution.

**Pull request closed without merging**
